### ISSUE TITLE
可否增加全拼搜索功能？

### ISSUE THREAD

**Issue by Baiyssy** [Chaoses-Ib/IbEverythingExt#19]
首字母重码太多了
谢谢！

**Comment by Chaoses-Ib** [comment]
没加全拼搜索主要是考虑到性能。目前拼音搜索的实现是基于正则字符组的，而增加全拼匹配会导致同一串字母可能匹配到不同长度的汉字，比如“na”既可以是“哪”也可以是“尼奥”，这样就必然要引入分支，但是 Everything 分支的性能非常差，字符组匹配 100 个候选汉字需要 2 秒，而分支需要 15 秒，这样就会带来非常大的性能下降，让本来就不好的性能雪上加霜。

Everything v1.5 Alpha 新增加的通配符字符组和分支语法可能会提高不少性能，如果最终性能比较理想的话会再考虑添加全拼搜索。

**Comment by Chaoses-Ib** [comment]
> #13
根据目前的测试来看，Everything v1.5 Alpha 的性能仍然不够理想，通配符字符组在字符较多时性能远不如正则表达式字符组，整体查询性能虽然提升了 30% 左右，但还是耗时很长。

目前暂时不会添加全拼搜索。

**Comment by ASC8384** [comment]
那请问会考虑用双拼规则下的声母搜索吗？
譬如小鹤双拼，`sh`简写为`u`

**Comment by Chaoses-Ib** [comment]
会好不少，但是这样功能性就要打个折扣，本身全拼输入相比输入法就只是免去了候选词的不确定性，如果还不能混合首拼，可能整体效率就比不过输入法了。

**Comment by Chaoses-Ib** [comment]
还是先等我测试完 PCRE 引擎吧，如果能成功的话就实现首拼全拼混合匹配，不行的话就只实现“首拼或全拼”匹配。到时会添加首拼、全拼和双拼的配置开关，可以自己选择使用哪几种。

**Comment by Baiyssy** [comment]
期待！

**Comment by ASC8384** [comment]
`ang`, 应当为 `ah`，其它的粗略一看都是正确的。

**Comment by Chaoses-Ib** [comment]
已支持全拼、带声调全拼、小鹤双拼：

![image](https://user-images.githubusercontent.com/50246090/140615140-f9377b9a-0f44-4bd9-a476-9df55498a4bd.png)

**Comment by Baiyssy** [comment]
可以设置个选项关掉双拼吗？用双拼的人毕竟是少数

**Comment by Chaoses-Ib** [comment]
双拼默认就是关闭的，配置见 develop 分支的 [README](https://github.com/Chaoses-Ib/IbEverythingExt/tree/develop)：
```yaml
# 拼音搜索
pinyin_search:
  enable: true
  mode: Auto  # Auto, Pcre, Edit
  initial: true  # 简拼
  pinyin_ascii: true  # 全拼
  pinyin_ascii_digit: true  # 带声调全拼
  double_pinyin_xiaohe: false  # 小鹤双拼
# 快速选择
quick_select:
  enable: true
```
